# Change these first
owner: qoreHQ # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository
user-agent: qoreHQ

sites:
  - name: qore.no
    url: https://qore.no
  - name: git.qore.no
    url: https://git.qore.no
  - name: beta.qore.no
    url: https://beta.qore.no
  - name: db.qore.no
    url: https://db.qore.no
  - name: 248.no
    url: https://248.no
  - name: actingquiet.com
    url: https://actingquiet.com
  - name: vagn.es
    url: https://vagn.es
  - name: rosvik.no
    url: https://rosvik.no

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: uptime.qore.no
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/qoreHQ/uptime/master/assets/icon-white.svg
  name: qoreUptime
  introTitle: "Uptime monitor for qore services"
  introMessage: This is a status page which uses real-time data from our [GitHub repository](https://github.com/qoreHQ/uptime). It is based on GitHub Actions, Issues, and Pages.
  navbar:
    - title: Home
      href: https://qore.no
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
